language: clojure
env:
  global:
  - secure: Pp26BmLJ3u1Hk6/HJQbUEzQOaIVLiAl3dee8YyoUnfeMj0zyuut/88HGT/EYYEhD7VCuVpLO7CoI2QcssUT/CczuB4uEDoncNAs4jMEzej5HJCr09CyYTjJlDgl1kZhScv7H9xbmuOPbev/VSMXNHviYEafaAvLKu6zfyDnwkaQAelgpx56NW/veNAQ6eiWk3SZ2EvblyfXP+Wz9qSZfuZwFexWniFsi1OqFtNOncvZNqQBbxD+7+2skMNe3BvCU0prPq/CdiA4i/V0LfLgoKvjwyyGV6JtOyKVxklyABCAYn+MMKdE1vfBvdhsKwj5RKLeLkM1rwFQ9yGb8zE/YGxoFN+kIa+/ZJB4tbAWKB/Uk5TL8cAsLorJmBWR6p8vzvLMrhVMN7CuEQVAqoGO4RdM8lzcLbggBFDc949oue095vIXWChV0Ht2cVe9XymJBB/ULoL0HtnIlREJ5tiNHXHRSvj9GP8VrRDOkHZhJuQDTYXAPozkHFVSUAbu5c2BJsde9nUTvYAkzMRBEQ7YSukkX08lpRKM5rooOH0Kefmp/X/Bd5CvzAsSyRE8mTk9tSw+kfxGAXXTDKaSCzoH4o2bHcj3p+jfXIcRzPtGo1ieVpV7KXmqo8hFJkr3g6lxY+zN8WNPznrWg6CaWhAZpMEn2uuzkRyQeWL0AAB5uZNI=
  - secure: kOR9sh9YdoLut7tDmcMaPR8FrJbJpWlhHS7aFKmJ7BqTS0N6pr7/y+inHBh8s435/wtXR9ayYr2YGmsm+WMNxU7AF76tsNgGioD0fSYUKWEEIwzn8WbxoI49NlsxUmZc3jtkjWX5+B1CeAtW0tvqw3nuhu8H+IcVFQBkk9JYY0uUK48SPRPm4YvpPdwLYH7n+QIO3/fsTM6mevkp2KtIyxGWvqumySYRGRVlMyQz1Tj2P/P/09YUiuHyZGvSeZcDDVa1uRRFj00Df9uJDVdurBqeCB7IXhN6iGmSK4zkXhiBLgymfsOzjkoByVA8vdFhdaOQCNgxCYKQCrXwid8Qaz6bjCfYKS5ZAo7+/I87NeyVRn5pVcScqZ5u5SnXQn3/RHQwVPuf/RcNjARE3dOwDMtlGiE7yCoNwa0/ayq3GSyLqmpFIhcIQ4/SfAaInXLS15ph7+kXPWHJC8s42hPy/KOaZIFS56hYs9tngosmAmx++CcWwvWGzf47on6P/2e8yi5IgqaCayrq6OY7Tu5hnOVruzVTsE8mBhOzJZXuMTInAedjg6kygfxYLmuAu5HoIPq1T/a9xiZo7EUbbt+T8LZytHhSrE05lCJRjEMONNGSltL39xpkfp83rtphxM+mP3La87ib0JK16+kvP7sJdr5tSb1vv5j9LFbHYfTuy54=
before_install:
- pip install --user awscli
- export PATH=$PATH:$HOME/.local/bin
install:
- lein uberjar
script:
- lein uberjar
- "./upload.sh"
